// =============================================================================
// MEEDOSys v2.0 - Complete Municipal Mock Dataset Faithful to Legacy
// =============================================================================

import {
  Stall,
  ElectricBill,
  SlaughterRecord,
  CemeteryBooking,
  Toda,
  TodaMember,
  OpifIndicator,
  CsuDailyReport,
  UserProfile,
} from '../types';

export const initialUsers: UserProfile[] = [
  {
    id: 'user_admin_01',
    username: 'admin',
    role: 'Admin',
    section: 'ALL',
    status: 'Approved',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user_staff_market',
    username: 'market_staff',
    role: 'Staff',
    section: 'A',
    status: 'Approved',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user_staff_slaughter',
    username: 'slaughter_staff',
    role: 'Staff',
    section: 'B',
    status: 'Approved',
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'user_staff_cemetery',
    username: 'cemetery_staff',
    role: 'Staff',
    section: 'C',
    status: 'Approved',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'user_staff_transport',
    username: 'transport_staff',
    role: 'Staff',
    section: 'D',
    status: 'Approved',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'user_staff_csu',
    username: 'guard_csu',
    role: 'Staff',
    section: 'F',
    status: 'Approved',
    created_at: '2024-03-15T00:00:00Z',
  },
];

// Helper to seed stalls
const createStall = (stall_no: string, zone: 'wet' | 'dry' | 'old' | 'triangular', isOccupied = false, owner = '', lob = ''): Stall => ({
  stall_no,
  zone,
  status: isOccupied ? 'Occupied' : 'Vacant',
  current_tenant: isOccupied
    ? {
        stall_no,
        stall_owner: owner || `Tenant ${stall_no}`,
        operator: owner || `Operator ${stall_no}`,
        line_of_business: lob || 'General Merchandise',
        period_index: 1,
        year: 2024,
        compliance_status: 'Compliant',
      }
    : null,
});

// Full stall directory matching legacy physical map
export const initialStalls: Stall[] = [
  // --- WET SECTION ---
  // Section G
  createStall('G-01-B', 'wet', true, 'Maria Clara Santos', 'Meat & Pork Cuts'),
  createStall('G-01-A', 'wet', true, 'Juan Dela Cruz', 'Pork & Beef Cuts'),
  createStall('G-02', 'wet', true, 'Pedro Penduko', 'Poultry Cuts'),
  createStall('G-10', 'wet', false),
  createStall('G-03', 'wet', true, 'Andres Bonifacio', 'Native Chicken'),
  createStall('G-11', 'wet', false),
  createStall('G-04', 'wet', true, 'Melchora Aquino', 'Dressed Chicken'),
  createStall('G-12', 'wet', false),
  createStall('G-05', 'wet', true, 'Emilio Jacinto', 'Fresh Fish'),
  createStall('G-13', 'wet', false),
  createStall('G-06', 'wet', true, 'Apolinario Mabini', 'Dried Fish (Bulad)'),
  createStall('G-14', 'wet', false),
  createStall('G-07', 'wet', true, 'Antonio Luna', 'Fresh Vegetables'),
  createStall('G-15', 'wet', false),
  createStall('G-08', 'wet', true, 'Marcelo H. Del Pilar', 'Root Crops'),
  createStall('G-16', 'wet', false),
  createStall('G-09', 'wet', true, 'Graciano Lopez Jaena', 'Spices & Condiments'),
  createStall('G-17', 'wet', false),

  // Section B & I
  createStall('B-01-A', 'wet', true, 'Josefa Llanes Escoda', 'Fresh Seafood'),
  createStall('B-01-B', 'wet', true, 'Teresa Magbanua', 'Shrimp & Crabs'),
  createStall('B-02', 'wet', true, 'Trinidad Tecson', 'Bangus & Tilapia'),
  createStall('B-06', 'wet', false),
  createStall('B-03', 'wet', true, 'Gregoria de Jesus', 'Fresh Pork'),
  createStall('B-07', 'wet', false),
  createStall('B-04', 'wet', true, 'Mariano Alvarez', 'Beef & Carabeef'),
  createStall('B-08', 'wet', false),
  createStall('B-05', 'wet', true, 'Vicente Lim', 'Poultry'),
  createStall('B-09', 'wet', false),
  createStall('I-01', 'wet', true, 'Ramon Magsaysay', 'Local Vegetables'),
  createStall('I-05', 'wet', false),
  createStall('I-02', 'wet', true, 'Manuel L. Quezon', 'Highland Produce'),
  createStall('I-06', 'wet', false),
  createStall('I-03', 'wet', true, 'Sergio Osmena', 'Onions & Garlic'),
  createStall('I-07', 'wet', false),
  createStall('I-04', 'wet', true, 'Manuel Roxas', 'Bananas & Fruits'),
  createStall('I-08', 'wet', false),

  // Section A & C
  createStall('A-01-A', 'wet', true, 'Jose Rizal', 'Rice Retailer'),
  createStall('A-01-B', 'wet', true, 'Paciano Rizal', 'Specialty Rice'),
  createStall('A-02', 'wet', true, 'Leonor Rivera', 'Corn Grits & Grains'),
  createStall('A-06', 'wet', false),
  createStall('A-03', 'wet', true, 'Concepcion Felix', 'Feeds & Grain'),
  createStall('A-07', 'wet', false),
  createStall('A-04', 'wet', true, 'Pura Villanueva Kalaw', 'Coconut & Copra'),
  createStall('A-08', 'wet', false),
  createStall('A-05', 'wet', true, 'Sofia Reyes de Veyra', 'Cooking Oil & Essentials'),
  createStall('A-09', 'wet', false),
  createStall('C-01', 'wet', true, 'Gliceria Marella de Villavicencio', 'Native Delicacies'),
  createStall('C-05', 'wet', false),
  createStall('C-02', 'wet', true, 'Agueda Esteban', 'Baking Needs'),
  createStall('C-06', 'wet', false),
  createStall('C-03', 'wet', true, 'Maria Orosa', 'Preserved Foods'),
  createStall('C-07', 'wet', false),
  createStall('C-04', 'wet', true, 'Magdalena Leones', 'Salt & Seasoning'),
  createStall('C-08', 'wet', false),

  // Special bottom stalls & Utilities
  createStall('LAND-BANK', 'wet', true, 'Land Bank of the Philippines', 'ATM & Banking Services'),
  createStall('MEEDO', 'wet', true, 'LGU Malungon', 'MEEDO Administrative Office'),
  createStall('E-08', 'wet', false),
  createStall('E-09', 'wet', false),

  // EF Grid
  createStall('E-01', 'wet', true, 'Arturo Tolentino', 'General Goods'),
  createStall('F-01', 'wet', true, 'Jose Diokno', 'Dry Fish'),
  createStall('E-02', 'wet', true, 'Lorenzo Tanada', 'Household Plastics'),
  createStall('F-02', 'wet', true, 'Jovito Salonga', 'Native Basketry'),
  createStall('E-03', 'wet', false),
  createStall('F-03', 'wet', false),
  createStall('E-04', 'wet', true, 'Claro M. Recto', 'Agricultural Seeds'),
  createStall('F-04', 'wet', true, 'Jose P. Laurel', 'Pest Control Needs'),
  createStall('E-05', 'wet', false),
  createStall('F-05', 'wet', false),
  createStall('E-06', 'wet', true, 'Camilo Osias', 'Kitchenware'),
  createStall('F-06', 'wet', true, 'Elpidio Quirino', 'Cooking Utensils'),
  createStall('E-07', 'wet', false),
  createStall('F-07', 'wet', false),

  // --- DRY GOODS SECTION ---
  // Second Floor Wings (D-01 to D-19)
  ...['D-19','D-18','D-17','D-16','D-15','D-14','D-13','D-12','D-11','D-10','D-09','D-08','D-07','D-06','D-05','D-04','D-03','D-02','D-01'].map(id =>
    createStall(id, 'dry', id === 'D-01' || id === 'D-05' || id === 'D-12', `Tenant ${id}`, 'Apparel & Textiles')
  ),
  // First Floor Wings (J-01 to J-08 and L-01 to L-09)
  ...['J-08','J-07','J-06','J-05','J-04','J-03','J-02','J-01'].map(id =>
    createStall(id, 'dry', id === 'J-01' || id === 'J-04', `Tenant ${id}`, 'Footwear & Bags')
  ),
  ...['L-09','L-08','L-07','L-06','L-05','L-04','L-03','L-02','L-01'].map(id =>
    createStall(id, 'dry', id === 'L-02' || id === 'L-07', `Tenant ${id}`, 'School & Office Supplies')
  ),

  // --- OLD BUILDING ---
  // Food Terminal (HE-1 to HE-8)
  ...['HE-1','HE-2','HE-3','HE-4','HE-5','HE-6','HE-7','HE-8'].map(id =>
    createStall(id, 'old', true, `Carenderia ${id}`, 'Cooked Meals & Refreshments')
  ),
  // Middle Complex (HE-9 to HE-22)
  ...['HE-9','HE-10','HE-11','HE-12','HE-13','HE-14','HE-15','HE-16','HE-17','HE-18','HE-19','HE-20','HE-21','HE-22'].map(id =>
    createStall(id, 'old', id === 'HE-9' || id === 'HE-12' || id === 'HE-18', `Complex Store ${id}`, 'Specialty Food')
  ),
  // High End 2nd Floor
  ...['F-10-HE', 'F-09-HE', 'F-08-HE', 'F-07-HE', 'F-06-HE', 'F-05-HE', 'F-01-HE', 'F-02-HE', 'F-03-04-HE'].map(id =>
    createStall(id, 'old', true, `Boutique ${id}`, 'Tailoring & Boutique')
  ),
  // High End 1st Floor
  ...['F1-08-HE', 'F1-05-HE', 'F1-07-HE', 'F1-04-HE', 'F1-06-HE', 'F1-01-HE', 'F1-03-HE', 'F1-02-HE'].map(id =>
    createStall(id, 'old', true, `Commercial ${id}`, 'Electronics & Accessories')
  ),

  // --- TRIANGULAR AREA ---
  // K-group
  ...['K-01', 'K-02', 'K-03', 'K-04', 'K-05', 'K-06-07', 'K-08', 'K-09', 'K-10', 'K-11', 'K-12'].map(id =>
    createStall(id, 'triangular', true, `Vendor ${id}`, 'Fruit Stands & Snacks')
  ),
  // Diagonal Staircase (D-20 to D-31)
  ...['D-31', 'D-30', 'D-28-29', 'D-27', 'D-26', 'D-25', 'D-24', 'D-23', 'D-22', 'D-21', 'D-20'].map(id =>
    createStall(id, 'triangular', true, `Tenant ${id}`, 'Commercial Hardware & Plastics')
  ),
  // Bottom Row (H-01 to H-15)
  ...['H-01', 'H-02-03', 'H-04-05', 'H-06', 'H-07', 'H-08-09', 'H-10-11', 'H-12-13', 'H-14-15'].map(id =>
    createStall(id, 'triangular', true, `Perimeter ${id}`, 'Beverages & Carenderia')
  ),
];

export const initialElectricBills: ElectricBill[] = [
  {
    id: 'bill_001',
    stall_no: 'G-01-A',
    owner_name: 'Juan Dela Cruz',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 150.0,
    curr_reading: 195.0,
    consumption: 45.0,
    rate_per_kwh: 15.0,
    arrears: 0.0,
    bill_amount: 675.0,
    status: 'Unpaid',
    created_at: '2024-09-30T08:00:00Z',
  },
  {
    id: 'bill_002',
    stall_no: 'G-01-B',
    owner_name: 'Maria Clara Santos',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 210.0,
    curr_reading: 242.0,
    consumption: 32.0,
    rate_per_kwh: 15.0,
    arrears: 150.0,
    bill_amount: 630.0,
    status: 'Fully Paid',
    created_at: '2024-09-30T08:15:00Z',
  },
  {
    id: 'bill_003',
    stall_no: 'D-01',
    owner_name: 'Tenant D-01',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 88.0,
    curr_reading: 104.0,
    consumption: 16.0,
    rate_per_kwh: 15.0,
    arrears: 0.0,
    bill_amount: 240.0,
    status: 'Unpaid',
    created_at: '2024-09-30T08:30:00Z',
  },
];

export const initialSlaughterRecords: SlaughterRecord[] = [
  {
    id: 'sh_001',
    client_id: 'C-001201',
    client_name: 'Reynaldo Meat Trading',
    contact_no: '0917-555-0101',
    or_number: 'OR-882190',
    status: 'Private',
    livestock_type: 'Hogs',
    head_count: 8,
    amount: 1200.0,
    created_at: '2024-09-08T04:30:00Z',
  },
  {
    id: 'sh_002',
    client_id: 'C-001202',
    client_name: 'Poblacion Butcher Coop',
    contact_no: '0928-555-0202',
    or_number: 'OR-882191',
    status: 'Public',
    livestock_type: 'Cow',
    head_count: 2,
    amount: 900.0,
    created_at: '2024-09-08T05:15:00Z',
  },
  {
    id: 'sh_003',
    client_id: 'C-001203',
    client_name: 'Malungon Native Goat Center',
    contact_no: '0908-555-0303',
    or_number: 'OR-882192',
    status: 'Private',
    livestock_type: 'Goat',
    head_count: 4,
    amount: 400.0,
    created_at: '2024-09-09T03:45:00Z',
  },
];

export const initialCemeteryBookings: CemeteryBooking[] = [
  {
    id: 'cem_001',
    deceased_name: 'Bernabe Ramirez',
    address_barangay: 'Poblacion',
    phone_number: '0919-444-1234',
    burial_date: '2024-09-12',
    burial_time: '14:00',
    burial_type: 'Apartment',
    amount: 2500.0,
    created_at: '2024-09-05T09:00:00Z',
  },
  {
    id: 'cem_002',
    deceased_name: 'Elena Salvador',
    address_barangay: 'Malandag',
    phone_number: '0922-333-5678',
    burial_date: '2024-09-15',
    burial_time: '10:00',
    burial_type: 'Ground',
    amount: 1800.0,
    created_at: '2024-09-06T11:30:00Z',
  },
  {
    id: 'cem_003',
    deceased_name: 'Conrado Villanueva',
    address_barangay: 'Banate',
    phone_number: '0918-777-8899',
    burial_date: '2024-09-20',
    burial_time: '15:30',
    burial_type: 'Bone Vault',
    amount: 1500.0,
    created_at: '2024-09-07T14:15:00Z',
  },
];

export const initialTodas: Toda[] = [
  {
    id: 'toda_01',
    reg_no: 'TODA-REG-2021-001',
    name: 'Poblacion Central Drivers & Operators TODA',
    president: 'Rodrigo Mendoza',
    contact_no: '0917-123-4567',
    total_members: 45,
    address: 'Terminal 1, Poblacion, Malungon',
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'toda_02',
    reg_no: 'TODA-REG-2022-004',
    name: 'Malandag Express Tricycle Association',
    president: 'Bernardo Carpio',
    contact_no: '0928-987-6543',
    total_members: 38,
    address: 'Malandag Public Market Highway, Malungon',
    created_at: '2024-02-05T00:00:00Z',
  },
];

export const initialTodaMembers: TodaMember[] = [
  {
    id: 'mem_01',
    toda_id: 'toda_01',
    toda_name: 'Poblacion Central Drivers & Operators TODA',
    last_name: 'Santos',
    first_name: 'Danilo',
    middle_name: 'Reyes',
    ext_name: 'Jr.',
    sex: 'Male',
    barangay: 'Poblacion',
    municipality: 'Malungon',
    contact_no: '0915-111-2233',
    id_type: "Driver's License",
    id_number: 'N02-14-123456',
    id_expiry: '2027-05-18',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'mem_02',
    toda_id: 'toda_01',
    toda_name: 'Poblacion Central Drivers & Operators TODA',
    last_name: 'Morales',
    first_name: 'Luzviminda',
    middle_name: 'Castro',
    ext_name: '',
    sex: 'Female',
    barangay: 'Poblacion',
    municipality: 'Malungon',
    contact_no: '0920-333-4455',
    id_type: "Driver's License",
    id_number: 'N02-18-654321',
    id_expiry: '2026-11-24',
    created_at: '2024-03-02T00:00:00Z',
  },
  {
    id: 'mem_03',
    toda_id: 'toda_02',
    toda_name: 'Malandag Express Tricycle Association',
    last_name: 'Castillo',
    first_name: 'Fernando',
    middle_name: 'Alvarez',
    ext_name: '',
    sex: 'Male',
    barangay: 'Malandag',
    municipality: 'Malungon',
    contact_no: '0912-777-8899',
    id_type: "Driver's License",
    id_number: 'N02-12-789012',
    id_expiry: '2025-08-10',
    created_at: '2024-03-10T00:00:00Z',
  },
];

// Complete official OPIF indicators directly from legacy/map_js.html
export const initialOpifIndicators: OpifIndicator[] = [
  // SECTION A: MARKET
  {
    id: 'opif_a_01',
    section: 'A',
    major_final_output: 'Optimal Revenue / Occupancy',
    performance_indicator: 'No. of lease contract checked and processed (New)',
    annual_target: '10',
    actual_annual: '5',
    semi_annual_target: '3',
    q1_target: '3',
    q1_actual: '3',
    q1_percent: '100%',
    q2_target: '2',
    q2_actual: '2',
    q2_percent: '100%',
    q3_target: '3',
    q3_actual: '3',
    q3_percent: '100%',
    q4_target: '2',
    q4_actual: '2',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_a_02',
    section: 'A',
    major_final_output: 'Optimal Revenue / Occupancy',
    performance_indicator: 'No. of lease contract checked and processed (Renew)',
    annual_target: '166',
    actual_annual: '166',
    semi_annual_target: '166',
    q1_target: '166',
    q1_actual: '166',
    q1_percent: '100%',
    q2_target: '0',
    q2_actual: '0',
    q2_percent: '100%',
    q3_target: '0',
    q3_actual: '0',
    q3_percent: '100%',
    q4_target: '0',
    q4_actual: '0',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_a_03',
    section: 'A',
    major_final_output: 'Market Operation / Stall Monitoring',
    performance_indicator: 'No. of stalls inspected & monitored for compliance',
    annual_target: '243',
    actual_annual: '243',
    semi_annual_target: '243',
    q1_target: '243',
    q1_actual: '243',
    q1_percent: '100%',
    q2_target: '243',
    q2_actual: '246',
    q2_percent: '101%',
    q3_target: '243',
    q3_actual: '245',
    q3_percent: '101%',
    q4_target: '243',
    q4_actual: '243',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_a_04',
    section: 'A',
    major_final_output: 'Market Operation / Open Space Monitoring',
    performance_indicator: 'No. of transient vendors facilitated in Barangays (Poblacion, Malandag & Banate)',
    annual_target: '162',
    actual_annual: '162',
    semi_annual_target: '191',
    q1_target: '162',
    q1_actual: '191',
    q1_percent: '118%',
    q2_target: '162',
    q2_actual: '193',
    q2_percent: '119%',
    q3_target: '162',
    q3_actual: '196',
    q3_percent: '121%',
    q4_target: '162',
    q4_actual: '192',
    q4_percent: '118%',
    year: 2024,
  },
  {
    id: 'opif_a_05',
    section: 'A',
    major_final_output: 'Sanitary, Orderly & Safety / Zoning',
    performance_indicator: 'No. of market stalls properly administered as to sectioning',
    annual_target: '243',
    actual_annual: '243',
    semi_annual_target: '243',
    q1_target: '243',
    q1_actual: '243',
    q1_percent: '100%',
    q2_target: '243',
    q2_actual: '246',
    q2_percent: '101%',
    q3_target: '243',
    q3_actual: '245',
    q3_percent: '101%',
    q4_target: '243',
    q4_actual: '243',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_a_06',
    section: 'A',
    major_final_output: 'Sanitary, Orderly & Safety / Facility Sanitation',
    performance_indicator: 'No. of stalls supervised & maintained as to premise cleanliness & proper sanitation',
    annual_target: '243',
    actual_annual: '243',
    semi_annual_target: '243',
    q1_target: '243',
    q1_actual: '243',
    q1_percent: '100%',
    q2_target: '243',
    q2_actual: '246',
    q2_percent: '101%',
    q3_target: '243',
    q3_actual: '245',
    q3_percent: '101%',
    q4_target: '243',
    q4_actual: '243',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_a_07',
    section: 'A',
    major_final_output: 'Regulatory Functions / Price Statistics',
    performance_indicator: 'No. of statistical data reports on prevailing prices prepared once a week',
    annual_target: '52',
    actual_annual: '26',
    semi_annual_target: '13',
    q1_target: '13',
    q1_actual: '13',
    q1_percent: '100%',
    q2_target: '13',
    q2_actual: '14',
    q2_percent: '108%',
    q3_target: '13',
    q3_actual: '13',
    q3_percent: '100%',
    q4_target: '13',
    q4_actual: '14',
    q4_percent: '108%',
    year: 2024,
  },

  // SECTION B: SLAUGHTERHOUSE
  {
    id: 'opif_b_01',
    section: 'B',
    major_final_output: 'Regulatory Functions / Meat Inspection',
    performance_indicator: 'No. of slaughtered animals conducted with ante-mortem and evisceration inspection',
    annual_target: '913',
    actual_annual: '457',
    semi_annual_target: '228',
    q1_target: '228',
    q1_actual: '256',
    q1_percent: '112%',
    q2_target: '229',
    q2_actual: '671',
    q2_percent: '293%',
    q3_target: '228',
    q3_actual: '256',
    q3_percent: '112%',
    q4_target: '229',
    q4_actual: '392',
    q4_percent: '171%',
    year: 2024,
  },
  {
    id: 'opif_b_02',
    section: 'B',
    major_final_output: 'Regulatory Functions / Certification',
    performance_indicator: 'No. of Meat Inspection Certificates issued',
    annual_target: '913',
    actual_annual: '457',
    semi_annual_target: '228',
    q1_target: '228',
    q1_actual: '256',
    q1_percent: '112%',
    q2_target: '229',
    q2_actual: '671',
    q2_percent: '293%',
    q3_target: '228',
    q3_actual: '256',
    q3_percent: '112%',
    q4_target: '229',
    q4_actual: '392',
    q4_percent: '171%',
    year: 2024,
  },
  {
    id: 'opif_b_03',
    section: 'B',
    major_final_output: 'Sanitation & Maintenance / Butcher Hygiene',
    performance_indicator: 'No. of days inspection of hygiene for butchers and scalding area done',
    annual_target: '363',
    actual_annual: '182',
    semi_annual_target: '90',
    q1_target: '91',
    q1_actual: '91',
    q1_percent: '100%',
    q2_target: '90',
    q2_actual: '91',
    q2_percent: '101%',
    q3_target: '91',
    q3_actual: '92',
    q3_percent: '101%',
    q4_target: '90',
    q4_actual: '92',
    q4_percent: '102%',
    year: 2024,
  },

  // SECTION C: CEMETERY
  {
    id: 'opif_c_01',
    section: 'C',
    major_final_output: 'Land Utilization / Occupancy',
    performance_indicator: 'No. of graveyards facilitated/allocated for occupancy based on Plan',
    annual_target: '40',
    actual_annual: '20',
    semi_annual_target: '10',
    q1_target: '15',
    q1_actual: '15',
    q1_percent: '100%',
    q2_target: '10',
    q2_actual: '20',
    q2_percent: '200%',
    q3_target: '10',
    q3_actual: '18',
    q3_percent: '180%',
    q4_target: '10',
    q4_actual: '19',
    q4_percent: '190%',
    year: 2024,
  },
  {
    id: 'opif_c_02',
    section: 'C',
    major_final_output: 'Land Utilization / Maintenance',
    performance_indicator: '100% of 3.6 has. cemetery land maintained at least once every quarter',
    annual_target: '3.6',
    actual_annual: '3.6',
    semi_annual_target: '3.6',
    q1_target: '3.6',
    q1_actual: '3.6',
    q1_percent: '100%',
    q2_target: '3.6',
    q2_actual: '3.6',
    q2_percent: '100%',
    q3_target: '3.6',
    q3_actual: '3.6',
    q3_percent: '100%',
    q4_target: '3.6',
    q4_actual: '3.6',
    q4_percent: '100%',
    year: 2024,
  },

  // SECTION D: TRANSPORT
  {
    id: 'opif_d_01',
    section: 'D',
    major_final_output: 'Terminal Operation / Inspection',
    performance_indicator: 'No. of Public Terminals Monitored & Inspected 3X a week',
    annual_target: '4',
    actual_annual: '4',
    semi_annual_target: '4',
    q1_target: '4',
    q1_actual: '4',
    q1_percent: '100%',
    q2_target: '4',
    q2_actual: '4',
    q2_percent: '100%',
    q3_target: '4',
    q3_actual: '4',
    q3_percent: '100%',
    q4_target: '4',
    q4_actual: '4',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_d_02',
    section: 'D',
    major_final_output: 'Regulatory Functions / Parking Fee Monitoring',
    performance_indicator: 'No. of vehicles monitored as to parking fee payment',
    annual_target: '4642',
    actual_annual: '4642',
    semi_annual_target: '4642',
    q1_target: '4642',
    q1_actual: '7643',
    q1_percent: '165%',
    q2_target: '4642',
    q2_actual: '7650',
    q2_percent: '165%',
    q3_target: '4642',
    q3_actual: '7435',
    q3_percent: '160%',
    q4_target: '4642',
    q4_actual: '7555',
    q4_percent: '163%',
    year: 2024,
  },

  // SECTION E: ADMIN SERVICES
  {
    id: 'opif_e_01',
    section: 'E',
    major_final_output: 'Administrative Governance / Communications',
    performance_indicator: 'No. of Communications, Memos, Activity Designs & Project Proposals submitted on time',
    annual_target: '20',
    actual_annual: '10',
    semi_annual_target: '5',
    q1_target: '5',
    q1_actual: '11',
    q1_percent: '220%',
    q2_target: '5',
    q2_actual: '7',
    q2_percent: '140%',
    q3_target: '5',
    q3_actual: '5',
    q3_percent: '100%',
    q4_target: '5',
    q4_actual: '6',
    q4_percent: '120%',
    year: 2024,
  },
  {
    id: 'opif_e_02',
    section: 'E',
    major_final_output: 'Procurement / Annual Procurement Plan',
    performance_indicator: 'Prepared and recommended for approval of 1 APP within timeframe',
    annual_target: '1',
    actual_annual: '1',
    semi_annual_target: '1',
    q1_target: '1',
    q1_actual: '1',
    q1_percent: '100%',
    q2_target: '0',
    q2_actual: '0',
    q2_percent: '100%',
    q3_target: '0',
    q3_actual: '0',
    q3_percent: '100%',
    q4_target: '0',
    q4_actual: '0',
    q4_percent: '100%',
    year: 2024,
  },
];

export const initialCsuReports: CsuDailyReport[] = [
  {
    id: 'csu_rep_01',
    report_date: '2024-09-08',
    day_of_week: 'Sunday',
    shift: '1st Shift (0600H - 1400H)',
    area_covered: 'Public Market Main Building & Wet Section Perimeter',
    summary_activities: 'Conducted regular security foot patrols, assisted elderly market-goers, monitored vendor unloading operations, and verified orderly tricycle queues at the entrance.',
    turnover_notes: 'Remind 2nd shift to monitor wet section drainage gates and ensure perimeter lights are activated by 1730H.',
    prep_name: 'SO2 Roberto Alcantara',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Gate 1 & Parking',
        time_in: '05:45',
        time_out: '14:00',
        remarks: 'On duty on time',
      },
      {
        guard_id: 'G-104',
        guard_name: 'Carlito Ramos',
        assigned_area: 'Wet Section Alley',
        time_in: '05:50',
        time_out: '14:00',
        remarks: 'Assisted market sanitation crew',
      },
    ],
    incident_data: [],
    violations_data: [
      {
        identifier: 'Transient Vendor #14',
        violation: 'Blocking pedestrian lane with produce crates',
        action_taken: 'Verbally reprimanded; vendor voluntarily cleared walkway',
        remarks: 'First offense',
      },
    ],
    lost_found_data: [
      {
        description: 'Black leather wallet with PhilHealth ID',
        found_by: 'Guard Alcantara (near Stall G-02-A)',
        claimed_by: 'Juanita Dela Cruz',
        status: 'Claimed',
      },
    ],
    created_at: '2024-09-08T14:10:00Z',
  },
  {
    id: 'csu_rep_02',
    report_date: '2024-09-07',
    day_of_week: 'Saturday',
    shift: '1st Shift (0600H - 1400H)',
    area_covered: 'Public Market Main Building, Food Terminal & Parking Area',
    summary_activities: 'Supervised Saturday market day foot traffic, maintained orderly vehicular flow at the Land Bank perimeter, assisted senior citizens.',
    turnover_notes: 'All terminal gates secured; night lights operational.',
    prep_name: 'SO2 Roberto Alcantara',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Gate 1 & Main Entrance',
        time_in: '05:50',
        time_out: '14:00',
        remarks: 'Maintained gate queue',
      },
      {
        guard_id: 'G-102',
        guard_name: 'Maria Santos',
        assigned_area: 'Food Terminal & Dry Goods',
        time_in: '06:00',
        time_out: '14:00',
        remarks: 'Foot patrol on 2nd floor',
      },
    ],
    incident_data: [
      {
        time: '09:30',
        location: 'Gate 1 Tricycle Bay',
        type: 'Minor Traffic Jam',
        description: 'Tricycle parked across unloading area. Driver directed to designated TODA holding line.',
        status: 'Resolved',
      },
    ],
    violations_data: [],
    lost_found_data: [],
    created_at: '2024-09-07T14:05:00Z',
  },
  {
    id: 'csu_rep_03',
    report_date: '2024-09-06',
    day_of_week: 'Friday',
    shift: '2nd Shift (1400H - 2200H)',
    area_covered: 'Public Market Perimeter & Meat Section',
    summary_activities: 'Conducted night lock-up inspection of all meat stalls and Section G stalls. Verified electrical breakers.',
    turnover_notes: 'All main gates padlocked at 2130H. Roving guard stationed at triangular post.',
    prep_name: 'SO1 Carlito Ramos',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-104',
        guard_name: 'Carlito Ramos',
        assigned_area: 'Meat & Wet Section Lockup',
        time_in: '13:55',
        time_out: '22:00',
        remarks: 'Completed closing inspection',
      },
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Perimeter Roving',
        time_in: '14:00',
        time_out: '22:00',
        remarks: 'Assisted night lockup',
      },
    ],
    incident_data: [],
    violations_data: [],
    lost_found_data: [],
    created_at: '2024-09-06T22:15:00Z',
  },
];
