// =============================================================================
// MEEDOSys v2.0 - Rich Municipal Mock Dataset for Offline Demo & Testing
// =============================================================================

import {
  Stall,
  ElectricBill,
  SlaughterRecord,
  CemeteryBooking,
  Toda,
  TodaMember,
  OpifIndicator,
  CsuDailyReport,
  UserProfile,
} from '../types';

export const initialUsers: UserProfile[] = [
  {
    id: 'user_admin_01',
    username: 'admin',
    role: 'Admin',
    section: 'ALL',
    status: 'Approved',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user_staff_market',
    username: 'market_staff',
    role: 'Staff',
    section: 'A',
    status: 'Approved',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user_staff_slaughter',
    username: 'slaughter_staff',
    role: 'Staff',
    section: 'B',
    status: 'Approved',
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'user_staff_cemetery',
    username: 'cemetery_staff',
    role: 'Staff',
    section: 'C',
    status: 'Approved',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'user_staff_transport',
    username: 'transport_staff',
    role: 'Staff',
    section: 'D',
    status: 'Approved',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'user_staff_csu',
    username: 'guard_csu',
    role: 'Staff',
    section: 'F',
    status: 'Approved',
    created_at: '2024-03-15T00:00:00Z',
  },
];

export const initialStalls: Stall[] = [
  // WET SECTION
  {
    stall_no: 'G-01-A',
    zone: 'wet',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'G-01-A',
      stall_owner: 'Maria Clara Santos',
      operator: 'Jose Rizal',
      line_of_business: 'Fresh Meat & Pork Cuts',
      period_index: 2,
      year: 2024,
      compliance_status: 'Compliant',
      photo_url: null,
      additional_info: 'Special butcher block license',
    },
    tenant_history: [
      {
        stall_no: 'G-01-A',
        stall_owner: 'Juanita Gomez',
        operator: 'Pedro Gomez',
        line_of_business: 'Fresh Pork',
        period_index: 1,
        year: 2022,
        compliance_status: 'Compliant',
      },
    ],
  },
  {
    stall_no: 'G-02-A',
    zone: 'wet',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'G-02-A',
      stall_owner: 'Juan Dela Cruz',
      operator: 'Juan Dela Cruz',
      line_of_business: 'Fresh Fish & Seafood',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },
  {
    stall_no: 'G-03-A',
    zone: 'wet',
    status: 'Vacant',
    current_tenant: null,
  },
  {
    stall_no: 'G-04-A',
    zone: 'wet',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'G-04-A',
      stall_owner: 'Andres Bonifacio',
      operator: 'Procuro',
      line_of_business: 'Native Vegetables',
      period_index: 1,
      year: 2024,
      compliance_status: 'Non-Compliant',
    },
  },
  {
    stall_no: 'G-05-A',
    zone: 'wet',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'G-05-A',
      stall_owner: 'Melchora Aquino',
      operator: 'Tandang Sora',
      line_of_business: 'Poultry & Dressed Chicken',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },
  {
    stall_no: 'G-06-A',
    zone: 'wet',
    status: 'Vacant',
    current_tenant: null,
  },

  // DRY GOODS
  {
    stall_no: 'D-01',
    zone: 'dry',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'D-01',
      stall_owner: 'Emilio Aguinaldo',
      operator: 'Emilio Aguinaldo',
      line_of_business: 'Footwear & School Supplies',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },
  {
    stall_no: 'D-02',
    zone: 'dry',
    status: 'Vacant',
    current_tenant: null,
  },
  {
    stall_no: 'D-03',
    zone: 'dry',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'D-03',
      stall_owner: 'Marcelo H. Del Pilar',
      operator: 'Plaridel Store',
      line_of_business: 'Ready-to-Wear (RTW) Clothing',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },

  // OLD BUILDING
  {
    stall_no: 'OB-01',
    zone: 'old',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'OB-01',
      stall_owner: 'Gabriela Silang',
      operator: 'Diego Silang',
      line_of_business: 'General Merchandise & Groceries',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },
  {
    stall_no: 'OB-02',
    zone: 'old',
    status: 'Vacant',
    current_tenant: null,
  },

  // TRIANGULAR AREA
  {
    stall_no: 'TR-01',
    zone: 'triangular',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'TR-01',
      stall_owner: 'Apolinario Mabini',
      operator: 'Mabini Eatery',
      line_of_business: 'Carenderia / Cooked Meals',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },
  {
    stall_no: 'TR-02',
    zone: 'triangular',
    status: 'Occupied',
    current_tenant: {
      stall_no: 'TR-02',
      stall_owner: 'Antonio Luna',
      operator: 'Luna Refreshments',
      line_of_business: 'Snacks & Fruit Shakes',
      period_index: 1,
      year: 2024,
      compliance_status: 'Compliant',
    },
  },
];

export const initialElectricBills: ElectricBill[] = [
  {
    id: 'bill_001',
    stall_no: 'G-01-A',
    owner_name: 'Maria Clara Santos',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 150.0,
    curr_reading: 195.0,
    consumption: 45.0,
    rate_per_kwh: 15.0,
    arrears: 0.0,
    bill_amount: 675.0,
    status: 'Unpaid',
    created_at: '2024-09-30T08:00:00Z',
  },
  {
    id: 'bill_002',
    stall_no: 'G-02-A',
    owner_name: 'Juan Dela Cruz',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 210.0,
    curr_reading: 242.0,
    consumption: 32.0,
    rate_per_kwh: 15.0,
    arrears: 150.0,
    bill_amount: 630.0,
    status: 'Fully Paid',
    created_at: '2024-09-30T08:15:00Z',
  },
  {
    id: 'bill_003',
    stall_no: 'D-01',
    owner_name: 'Emilio Aguinaldo',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 88.0,
    curr_reading: 104.0,
    consumption: 16.0,
    rate_per_kwh: 15.0,
    arrears: 0.0,
    bill_amount: 240.0,
    status: 'Unpaid',
    created_at: '2024-09-30T08:30:00Z',
  },
];

export const initialSlaughterRecords: SlaughterRecord[] = [
  {
    id: 'sh_001',
    client_id: 'C-001201',
    client_name: 'Reynaldo Meat Trading',
    contact_no: '0917-555-0101',
    or_number: 'OR-882190',
    status: 'Private',
    livestock_type: 'Hogs',
    head_count: 8,
    amount: 1200.0,
    created_at: '2024-09-08T04:30:00Z',
  },
  {
    id: 'sh_002',
    client_id: 'C-001202',
    client_name: 'Poblacion Butcher Coop',
    contact_no: '0928-555-0202',
    or_number: 'OR-882191',
    status: 'Public',
    livestock_type: 'Cow',
    head_count: 2,
    amount: 900.0,
    created_at: '2024-09-08T05:15:00Z',
  },
  {
    id: 'sh_003',
    client_id: 'C-001203',
    client_name: 'Malungon Native Goat Center',
    contact_no: '0908-555-0303',
    or_number: 'OR-882192',
    status: 'Private',
    livestock_type: 'Goat',
    head_count: 4,
    amount: 400.0,
    created_at: '2024-09-09T03:45:00Z',
  },
];

export const initialCemeteryBookings: CemeteryBooking[] = [
  {
    id: 'cem_001',
    deceased_name: 'Bernabe Ramirez',
    address_barangay: 'Poblacion',
    phone_number: '0919-444-1234',
    burial_date: '2024-09-12',
    burial_time: '14:00',
    burial_type: 'Apartment',
    amount: 2500.0,
    created_at: '2024-09-05T09:00:00Z',
  },
  {
    id: 'cem_002',
    deceased_name: 'Elena Salvador',
    address_barangay: 'Malandag',
    phone_number: '0922-333-5678',
    burial_date: '2024-09-15',
    burial_time: '10:00',
    burial_type: 'Ground',
    amount: 1800.0,
    created_at: '2024-09-06T11:30:00Z',
  },
  {
    id: 'cem_003',
    deceased_name: 'Conrado Villanueva',
    address_barangay: 'Banate',
    phone_number: '0918-777-8899',
    burial_date: '2024-09-20',
    burial_time: '15:30',
    burial_type: 'Bone Vault',
    amount: 1500.0,
    created_at: '2024-09-07T14:15:00Z',
  },
];

export const initialTodas: Toda[] = [
  {
    id: 'toda_01',
    reg_no: 'TODA-REG-2021-001',
    name: 'Poblacion Central Drivers & Operators TODA',
    president: 'Rodrigo Mendoza',
    contact_no: '0917-123-4567',
    total_members: 45,
    address: 'Terminal 1, Poblacion, Malungon',
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'toda_02',
    reg_no: 'TODA-REG-2022-004',
    name: 'Malandag Express Tricycle Association',
    president: 'Bernardo Carpio',
    contact_no: '0928-987-6543',
    total_members: 38,
    address: 'Malandag Public Market Highway, Malungon',
    created_at: '2024-02-05T00:00:00Z',
  },
];

export const initialTodaMembers: TodaMember[] = [
  {
    id: 'mem_01',
    toda_id: 'toda_01',
    toda_name: 'Poblacion Central Drivers & Operators TODA',
    last_name: 'Santos',
    first_name: 'Danilo',
    middle_name: 'Reyes',
    ext_name: 'Jr.',
    sex: 'Male',
    barangay: 'Poblacion',
    municipality: 'Malungon',
    contact_no: '0915-111-2233',
    id_type: "Driver's License",
    id_number: 'N02-14-123456',
    id_expiry: '2027-05-18',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'mem_02',
    toda_id: 'toda_01',
    toda_name: 'Poblacion Central Drivers & Operators TODA',
    last_name: 'Morales',
    first_name: 'Luzviminda',
    middle_name: 'Castro',
    ext_name: '',
    sex: 'Female',
    barangay: 'Poblacion',
    municipality: 'Malungon',
    contact_no: '0920-333-4455',
    id_type: "Driver's License",
    id_number: 'N02-18-654321',
    id_expiry: '2026-11-24',
    created_at: '2024-03-02T00:00:00Z',
  },
  {
    id: 'mem_03',
    toda_id: 'toda_02',
    toda_name: 'Malandag Express Tricycle Association',
    last_name: 'Castillo',
    first_name: 'Fernando',
    middle_name: 'Alvarez',
    ext_name: '',
    sex: 'Male',
    barangay: 'Malandag',
    municipality: 'Malungon',
    contact_no: '0912-777-8899',
    id_type: "Driver's License",
    id_number: 'N02-12-789012',
    id_expiry: '2025-08-10',
    created_at: '2024-03-10T00:00:00Z',
  },
];

export const initialOpifIndicators: OpifIndicator[] = [
  // SECTION A
  {
    id: 'opif_01',
    section: 'A',
    major_final_output: 'Optimal Revenue & Stall Administration',
    performance_indicator: 'No. of lease contracts checked and processed (New)',
    annual_target: '10',
    actual_annual: '5',
    semi_annual_target: '3',
    q1_target: '3',
    q1_actual: '3',
    q1_percent: '100%',
    q2_target: '2',
    q2_actual: '2',
    q2_percent: '100%',
    q3_target: '3',
    q3_actual: '3',
    q3_percent: '100%',
    q4_target: '2',
    q4_actual: '2',
    q4_percent: '100%',
    year: 2024,
  },
  {
    id: 'opif_02',
    section: 'A',
    major_final_output: 'Market Operations & Monitoring',
    performance_indicator: 'No. of stalls inspected & monitored for compliance',
    annual_target: '243',
    actual_annual: '243',
    semi_annual_target: '243',
    q1_target: '243',
    q1_actual: '243',
    q1_percent: '100%',
    q2_target: '243',
    q2_actual: '246',
    q2_percent: '101%',
    q3_target: '243',
    q3_actual: '245',
    q3_percent: '101%',
    q4_target: '243',
    q4_actual: '243',
    q4_percent: '100%',
    year: 2024,
  },
  // SECTION B
  {
    id: 'opif_03',
    section: 'B',
    major_final_output: 'Slaughterhouse Quality & Hygiene',
    performance_indicator: 'No. of slaughtered animals conducted with ante-mortem inspection',
    annual_target: '913',
    actual_annual: '457',
    semi_annual_target: '228',
    q1_target: '228',
    q1_actual: '256',
    q1_percent: '112%',
    q2_target: '229',
    q2_actual: '671',
    q2_percent: '293%',
    q3_target: '228',
    q3_actual: '256',
    q3_percent: '112%',
    q4_target: '229',
    q4_actual: '392',
    q4_percent: '171%',
    year: 2024,
  },
  // SECTION C
  {
    id: 'opif_04',
    section: 'C',
    major_final_output: 'Cemetery Land Utilization',
    performance_indicator: 'No. of graveyards facilitated/allocated for occupancy',
    annual_target: '40',
    actual_annual: '20',
    semi_annual_target: '10',
    q1_target: '15',
    q1_actual: '15',
    q1_percent: '100%',
    q2_target: '10',
    q2_actual: '20',
    q2_percent: '200%',
    q3_target: '10',
    q3_actual: '18',
    q3_percent: '180%',
    q4_target: '10',
    q4_actual: '19',
    q4_percent: '190%',
    year: 2024,
  },
];

export const initialCsuReports: CsuDailyReport[] = [
  {
    id: 'csu_rep_01',
    report_date: '2024-09-08',
    day_of_week: 'Sunday',
    shift: '1st Shift (0600H - 1400H)',
    area_covered: 'Public Market Main Building & Wet Section Perimeter',
    summary_activities: 'Conducted regular security foot patrols, assisted elderly market-goers, monitored vendor unloading operations, and verified orderly tricycle queues at the entrance.',
    turnover_notes: 'Remind 2nd shift to monitor wet section drainage gates and ensure perimeter lights are activated by 1730H.',
    prep_name: 'SO2 Roberto Alcantara',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Gate 1 & Parking',
        time_in: '05:45',
        time_out: '14:00',
        remarks: 'On duty on time',
      },
      {
        guard_id: 'G-104',
        guard_name: 'Carlito Ramos',
        assigned_area: 'Wet Section Alley',
        time_in: '05:50',
        time_out: '14:00',
        remarks: 'Assisted market sanitation crew',
      },
    ],
    incident_data: [],
    violations_data: [
      {
        identifier: 'Transient Vendor #14',
        violation: 'Blocking pedestrian lane with produce crates',
        action_taken: 'Verbally reprimanded; vendor voluntarily cleared walkway',
        remarks: 'First offense',
      },
    ],
    lost_found_data: [
      {
        description: 'Black leather wallet with PhilHealth ID',
        found_by: 'Guard Alcantara (near Stall G-02-A)',
        claimed_by: 'Juanita Dela Cruz',
        status: 'Claimed',
      },
    ],
    created_at: '2024-09-08T14:10:00Z',
  },
];
