// =============================================================================
// MEEDOSys v2.0 - Complete Municipal Mock Dataset Faithful to Legacy
// =============================================================================

import {
  Stall,
  ElectricBill,
  SlaughterRecord,
  CemeteryBooking,
  Toda,
  TodaMember,
  OpifIndicator,
  CsuDailyReport,
  UserProfile,
  MarketGuard,
  InventoryItem,
  InventoryTransaction,
  ButcherProfile,
} from '../types';

export const initialUsers: UserProfile[] = [
  {
    id: 'user_admin_01',
    username: 'admin',
    role: 'Admin',
    section: 'ALL',
    status: 'Approved',
    full_name: 'Hon. Market Administrator',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user_staff_market',
    username: 'market_staff',
    role: 'Staff',
    section: 'A',
    status: 'Approved',
    full_name: 'Juan Dela Cruz (Market)',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user_staff_slaughter',
    username: 'slaughter_staff',
    role: 'Staff',
    section: 'B',
    status: 'Approved',
    full_name: 'Pedro Penduko (Slaughterhouse)',
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'user_staff_cemetery',
    username: 'cemetery_staff',
    role: 'Staff',
    section: 'C',
    status: 'Approved',
    full_name: 'Clara Santos (Cemetery)',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'user_staff_transport',
    username: 'transport_staff',
    role: 'Staff',
    section: 'D',
    status: 'Approved',
    full_name: 'Ramon Bautista (Transport)',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'user_staff_opif',
    username: 'opif_staff',
    role: 'Staff',
    section: 'E',
    status: 'Approved',
    full_name: 'Elena Morales (Executive/OPIF)',
    created_at: '2024-03-05T00:00:00Z',
  },
  {
    id: 'user_staff_guard',
    username: 'guard_market',
    role: 'Staff',
    section: 'F',
    status: 'Approved',
    guard_id: 'G-101',
    full_name: 'Roberto Alcantara',
    rank_title: 'SO2',
    created_at: '2024-03-15T00:00:00Z',
  },
  {
    id: 'user_staff_csu_legacy',
    username: 'guard_csu',
    role: 'Staff',
    section: 'F',
    status: 'Approved',
    guard_id: 'G-101',
    full_name: 'Roberto Alcantara',
    rank_title: 'SO2',
    created_at: '2024-03-15T00:00:00Z',
  },
];

// Helper to seed stalls
const createStall = (stall_no: string, zone: 'wet' | 'dry' | 'old' | 'triangular', isOccupied = false, owner = '', lob = ''): Stall => ({
  stall_no,
  zone,
  status: isOccupied ? 'Occupied' : 'Vacant',
  current_tenant: isOccupied
    ? {
        stall_no,
        stall_owner: owner || `Tenant ${stall_no}`,
        operator: owner || `Operator ${stall_no}`,
        line_of_business: lob || 'General Merchandise',
        period_index: 1,
        year: 2024,
        compliance_status: 'Compliant',
      }
    : null,
});

// Full stall directory matching legacy physical map
export const initialStalls: Stall[] = [
  // --- WET SECTION ---
  // Section G
  createStall('G-01-B', 'wet', true, 'Maria Clara Santos', 'Meat & Pork Cuts'),
  createStall('G-01-A', 'wet', true, 'Juan Dela Cruz', 'Pork & Beef Cuts'),
  createStall('G-02', 'wet', true, 'Pedro Penduko', 'Poultry Cuts'),
  createStall('G-10', 'wet', false),
  createStall('G-03', 'wet', true, 'Andres Bonifacio', 'Native Chicken'),
  createStall('G-11', 'wet', false),
  createStall('G-04', 'wet', true, 'Melchora Aquino', 'Dressed Chicken'),
  createStall('G-12', 'wet', false),
  createStall('G-05', 'wet', true, 'Emilio Jacinto', 'Fresh Fish'),
  createStall('G-13', 'wet', false),
  createStall('G-06', 'wet', true, 'Apolinario Mabini', 'Dried Fish (Bulad)'),
  createStall('G-14', 'wet', false),
  createStall('G-07', 'wet', true, 'Antonio Luna', 'Fresh Vegetables'),
  createStall('G-15', 'wet', false),
  createStall('G-08', 'wet', true, 'Marcelo H. Del Pilar', 'Root Crops'),
  createStall('G-16', 'wet', false),
  createStall('G-09', 'wet', true, 'Graciano Lopez Jaena', 'Spices & Condiments'),
  createStall('G-17', 'wet', false),

  // Section B & I
  createStall('B-01-A', 'wet', true, 'Josefa Llanes Escoda', 'Fresh Seafood'),
  createStall('B-01-B', 'wet', true, 'Teresa Magbanua', 'Shrimp & Crabs'),
  createStall('B-02', 'wet', true, 'Trinidad Tecson', 'Bangus & Tilapia'),
  createStall('B-06', 'wet', false),
  createStall('B-03', 'wet', true, 'Gregoria de Jesus', 'Fresh Pork'),
  createStall('B-07', 'wet', false),
  createStall('B-04', 'wet', true, 'Mariano Alvarez', 'Beef & Carabeef'),
  createStall('B-08', 'wet', false),
  createStall('B-05', 'wet', true, 'Vicente Lim', 'Poultry'),
  createStall('B-09', 'wet', false),
  createStall('I-01', 'wet', true, 'Ramon Magsaysay', 'Local Vegetables'),
  createStall('I-05', 'wet', false),
  createStall('I-02', 'wet', true, 'Manuel L. Quezon', 'Highland Produce'),
  createStall('I-06', 'wet', false),
  createStall('I-03', 'wet', true, 'Sergio Osmena', 'Onions & Garlic'),
  createStall('I-07', 'wet', false),
  createStall('I-04', 'wet', true, 'Manuel Roxas', 'Bananas & Fruits'),
  createStall('I-08', 'wet', false),

  // Section A & C
  createStall('A-01-A', 'wet', true, 'Jose Rizal', 'Rice Retailer'),
  createStall('A-01-B', 'wet', true, 'Paciano Rizal', 'Specialty Rice'),
  createStall('A-02', 'wet', true, 'Leonor Rivera', 'Corn Grits & Grains'),
  createStall('A-06', 'wet', false),
  createStall('A-03', 'wet', true, 'Concepcion Felix', 'Feeds & Grain'),
  createStall('A-07', 'wet', false),
  createStall('A-04', 'wet', true, 'Pura Villanueva Kalaw', 'Coconut & Copra'),
  createStall('A-08', 'wet', false),
  createStall('A-05', 'wet', true, 'Sofia Reyes de Veyra', 'Cooking Oil & Essentials'),
  createStall('A-09', 'wet', false),
  createStall('C-01', 'wet', true, 'Gliceria Marella de Villavicencio', 'Native Delicacies'),
  createStall('C-05', 'wet', false),
  createStall('C-02', 'wet', true, 'Agueda Esteban', 'Baking Needs'),
  createStall('C-06', 'wet', false),
  createStall('C-03', 'wet', true, 'Maria Orosa', 'Preserved Foods'),
  createStall('C-07', 'wet', false),
  createStall('C-04', 'wet', true, 'Magdalena Leones', 'Salt & Seasoning'),
  createStall('C-08', 'wet', false),

  // Special bottom stalls & Utilities
  createStall('LAND-BANK', 'wet', true, 'Land Bank of the Philippines', 'ATM & Banking Services'),
  createStall('MEEDO', 'wet', true, 'LGU Malungon', 'MEEDO Administrative Office'),
  createStall('E-08', 'wet', false),
  createStall('E-09', 'wet', false),

  // EF Grid
  createStall('E-01', 'wet', true, 'Arturo Tolentino', 'General Goods'),
  createStall('F-01', 'wet', true, 'Jose Diokno', 'Dry Fish'),
  createStall('E-02', 'wet', true, 'Lorenzo Tanada', 'Household Plastics'),
  createStall('F-02', 'wet', true, 'Jovito Salonga', 'Native Basketry'),
  createStall('E-03', 'wet', false),
  createStall('F-03', 'wet', false),
  createStall('E-04', 'wet', true, 'Claro M. Recto', 'Agricultural Seeds'),
  createStall('F-04', 'wet', true, 'Jose P. Laurel', 'Pest Control Needs'),
  createStall('E-05', 'wet', false),
  createStall('F-05', 'wet', false),
  createStall('E-06', 'wet', true, 'Camilo Osias', 'Kitchenware'),
  createStall('F-06', 'wet', true, 'Elpidio Quirino', 'Cooking Utensils'),
  createStall('E-07', 'wet', false),
  createStall('F-07', 'wet', false),

  // --- DRY GOODS SECTION ---
  // Second Floor Wings (D-01 to D-19)
  ...['D-19','D-18','D-17','D-16','D-15','D-14','D-13','D-12','D-11','D-10','D-09','D-08','D-07','D-06','D-05','D-04','D-03','D-02','D-01'].map(id =>
    createStall(id, 'dry', id === 'D-01' || id === 'D-05' || id === 'D-12', `Tenant ${id}`, 'Apparel & Textiles')
  ),
  // First Floor Wings (J-01 to J-08 and L-01 to L-09)
  ...['J-08','J-07','J-06','J-05','J-04','J-03','J-02','J-01'].map(id =>
    createStall(id, 'dry', id === 'J-01' || id === 'J-04', `Tenant ${id}`, 'Footwear & Bags')
  ),
  ...['L-09','L-08','L-07','L-06','L-05','L-04','L-03','L-02','L-01'].map(id =>
    createStall(id, 'dry', id === 'L-02' || id === 'L-07', `Tenant ${id}`, 'School & Office Supplies')
  ),

  // --- OLD BUILDING ---
  // Food Terminal (HE-1 to HE-8)
  ...['HE-1','HE-2','HE-3','HE-4','HE-5','HE-6','HE-7','HE-8'].map(id =>
    createStall(id, 'old', true, `Carenderia ${id}`, 'Cooked Meals & Refreshments')
  ),
  // Middle Complex (HE-9 to HE-22)
  ...['HE-9','HE-10','HE-11','HE-12','HE-13','HE-14','HE-15','HE-16','HE-17','HE-18','HE-19','HE-20','HE-21','HE-22'].map(id =>
    createStall(id, 'old', id === 'HE-9' || id === 'HE-12' || id === 'HE-18', `Complex Store ${id}`, 'Specialty Food')
  ),
  // High End 2nd Floor
  ...['F-10-HE', 'F-09-HE', 'F-08-HE', 'F-07-HE', 'F-06-HE', 'F-05-HE', 'F-01-HE', 'F-02-HE', 'F-03-04-HE'].map(id =>
    createStall(id, 'old', true, `Boutique ${id}`, 'Tailoring & Boutique')
  ),
  // High End 1st Floor
  ...['F1-08-HE', 'F1-05-HE', 'F1-07-HE', 'F1-04-HE', 'F1-06-HE', 'F1-01-HE', 'F1-03-HE', 'F1-02-HE'].map(id =>
    createStall(id, 'old', true, `Commercial ${id}`, 'Electronics & Accessories')
  ),

  // --- TRIANGULAR AREA ---
  // K-group
  ...['K-01', 'K-02', 'K-03', 'K-04', 'K-05', 'K-06-07', 'K-08', 'K-09', 'K-10', 'K-11', 'K-12'].map(id =>
    createStall(id, 'triangular', true, `Vendor ${id}`, 'Fruit Stands & Snacks')
  ),
  // Diagonal Staircase (D-20 to D-31)
  ...['D-31', 'D-30', 'D-28-29', 'D-27', 'D-26', 'D-25', 'D-24', 'D-23', 'D-22', 'D-21', 'D-20'].map(id =>
    createStall(id, 'triangular', true, `Tenant ${id}`, 'Commercial Hardware & Plastics')
  ),
  // Bottom Row (H-01 to H-15)
  ...['H-01', 'H-02-03', 'H-04-05', 'H-06', 'H-07', 'H-08-09', 'H-10-11', 'H-12-13', 'H-14-15'].map(id =>
    createStall(id, 'triangular', true, `Perimeter ${id}`, 'Beverages & Carenderia')
  ),
];

export const initialElectricBills: ElectricBill[] = [
  {
    id: 'bill_001',
    stall_no: 'G-01-A',
    owner_name: 'Juan Dela Cruz',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 150.0,
    curr_reading: 195.0,
    consumption: 45.0,
    rate_per_kwh: 15.0,
    arrears: 0.0,
    bill_amount: 675.0,
    status: 'Unpaid',
    created_at: '2024-09-30T08:00:00Z',
  },
  {
    id: 'bill_002',
    stall_no: 'G-01-B',
    owner_name: 'Maria Clara Santos',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 210.0,
    curr_reading: 242.0,
    consumption: 32.0,
    rate_per_kwh: 15.0,
    arrears: 150.0,
    bill_amount: 630.0,
    status: 'Fully Paid',
    created_at: '2024-09-30T08:15:00Z',
  },
  {
    id: 'bill_003',
    stall_no: 'D-01',
    owner_name: 'Tenant D-01',
    due_date: '2024-10-15',
    disconnection_date: '2024-10-20',
    prev_reading: 88.0,
    curr_reading: 104.0,
    consumption: 16.0,
    rate_per_kwh: 15.0,
    arrears: 0.0,
    bill_amount: 240.0,
    status: 'Unpaid',
    created_at: '2024-09-30T08:30:00Z',
  },
];

export const initialButchers: ButcherProfile[] = [];


export const initialSlaughterRecords: SlaughterRecord[] = [
  {
    id: 'sh_001',
    client_id: 'C-001201',
    client_name: 'Reynaldo Meat Trading',
    address: 'Poblacion, Malungon',
    contact_no: '0917-555-0101',
    or_number: 'OR-882190',
    status: 'Private',
    livestock_type: 'Hogs',
    head_count: 8,
    kilos: 640.0,
    amount: 1200.0,
    butcher_id: 'btc_001',
    butcher_name: 'Danilo "Danny" Fernandez',
    created_at: '2024-09-08T04:30:00Z',
  },
  {
    id: 'sh_002',
    client_id: 'C-001202',
    client_name: 'Poblacion Butcher Coop',
    address: 'Malandag, Malungon',
    contact_no: '0928-555-0202',
    or_number: 'OR-882191',
    status: 'Public',
    livestock_type: 'Cow',
    head_count: 2,
    kilos: 520.0,
    amount: 900.0,
    butcher_id: 'btc_002',
    butcher_name: 'Roberto "Bert" Sison',
    created_at: '2024-09-08T05:15:00Z',
  },
  {
    id: 'sh_003',
    client_id: 'C-001203',
    client_name: 'Malungon Native Goat Center',
    address: 'Banate, Malungon',
    contact_no: '0908-555-0303',
    or_number: 'OR-882192',
    status: 'Private',
    livestock_type: 'Goat',
    head_count: 4,
    kilos: 88.0,
    amount: 400.0,
    butcher_id: 'btc_003',
    butcher_name: 'Eduardo "Eddie" Morales',
    created_at: '2024-09-09T03:45:00Z',
  },
  {
    id: 'sh_004',
    client_id: 'C-001204',
    client_name: 'Amparo Dressed Poultry',
    address: 'Amparo, Malungon',
    contact_no: '0912-333-4455',
    or_number: 'OR-882193',
    status: 'Private',
    livestock_type: 'Chicken',
    head_count: 25,
    kilos: 37.5,
    amount: 500.0,
    butcher_id: 'btc_005',
    butcher_name: 'Arturo "Turing" Gonzaga',
    created_at: '2024-09-10T02:00:00Z',
  },
];

export const initialCemeteryBookings: CemeteryBooking[] = [
  {
    id: 'cem_001',
    deceased_name: 'Bernabe Ramirez',
    address_barangay: 'Poblacion',
    phone_number: '0919-444-1234',
    burial_date: '2024-09-12',
    burial_time: '14:00',
    burial_type: 'Apartment',
    amount: 2500.0,
    created_at: '2024-09-05T09:00:00Z',
  },
  {
    id: 'cem_002',
    deceased_name: 'Elena Salvador',
    address_barangay: 'Malandag',
    phone_number: '0922-333-5678',
    burial_date: '2024-09-15',
    burial_time: '10:00',
    burial_type: 'Ground',
    amount: 1800.0,
    created_at: '2024-09-06T11:30:00Z',
  },
  {
    id: 'cem_003',
    deceased_name: 'Conrado Villanueva',
    address_barangay: 'Banate',
    phone_number: '0918-777-8899',
    burial_date: '2024-09-20',
    burial_time: '15:30',
    burial_type: 'Bone Vault',
    amount: 1500.0,
    created_at: '2024-09-07T14:15:00Z',
  },
];

export const initialTodas: Toda[] = [
  {
    id: 'toda_01',
    reg_no: 'TODA-REG-2021-001',
    name: 'Poblacion Central Drivers & Operators TODA',
    president: 'Rodrigo Mendoza',
    contact_no: '0917-123-4567',
    total_members: 45,
    address: 'Terminal 1, Poblacion, Malungon',
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'toda_02',
    reg_no: 'TODA-REG-2022-004',
    name: 'Malandag Express Tricycle Association',
    president: 'Bernardo Carpio',
    contact_no: '0928-987-6543',
    total_members: 38,
    address: 'Malandag Public Market Highway, Malungon',
    created_at: '2024-02-05T00:00:00Z',
  },
];

export const initialTodaMembers: TodaMember[] = [
  {
    id: 'mem_01',
    toda_id: 'toda_01',
    toda_name: 'Poblacion Central Drivers & Operators TODA',
    last_name: 'Santos',
    first_name: 'Danilo',
    middle_name: 'Reyes',
    ext_name: 'Jr.',
    sex: 'Male',
    barangay: 'Poblacion',
    municipality: 'Malungon',
    contact_no: '0915-111-2233',
    id_type: "Driver's License",
    id_number: 'N02-14-123456',
    id_expiry: '2027-05-18',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'mem_02',
    toda_id: 'toda_01',
    toda_name: 'Poblacion Central Drivers & Operators TODA',
    last_name: 'Morales',
    first_name: 'Luzviminda',
    middle_name: 'Castro',
    ext_name: '',
    sex: 'Female',
    barangay: 'Poblacion',
    municipality: 'Malungon',
    contact_no: '0920-333-4455',
    id_type: "Driver's License",
    id_number: 'N02-18-654321',
    id_expiry: '2026-11-24',
    created_at: '2024-03-02T00:00:00Z',
  },
  {
    id: 'mem_03',
    toda_id: 'toda_02',
    toda_name: 'Malandag Express Tricycle Association',
    last_name: 'Castillo',
    first_name: 'Fernando',
    middle_name: 'Alvarez',
    ext_name: '',
    sex: 'Male',
    barangay: 'Malandag',
    municipality: 'Malungon',
    contact_no: '0912-777-8899',
    id_type: "Driver's License",
    id_number: 'N02-12-789012',
    id_expiry: '2025-08-10',
    created_at: '2024-03-10T00:00:00Z',
  },
];

// Complete official OPIF indicators directly from legacy/map_js.html
export const initialOpifIndicators: OpifIndicator[] = [
  // SECTION A: MARKET MANAGEMENT (11 rows)
  {
    id: 'opif_a_01',
    section: 'A',
    col3: 'Optimal Revenue',
    col4: 'Occupancy',
    col5: 'No. of lease contract checked and processed',
    col6: 'New',
    col7: '10',
    actual: '5',
    semi: '3',
    q1t: '3', q1a: '3', q1p: '100%',
    q2t: '2', q2a: '2', q2p: '100%',
    q3t: '3', q3a: '3', q3p: '100%',
    q4t: '2', q4a: '2', q4p: '100%',
    major_final_output: 'Occupancy',
    performance_indicator: 'New',
    annual_target: '10',
    year: 2025,
  },
  {
    id: 'opif_a_02',
    section: 'A',
    col3: 'Optimal Revenue',
    col4: 'Occupancy',
    col5: 'No. of lease contract checked and processed',
    col6: 'Renew',
    col7: '166',
    actual: '166',
    semi: '166',
    specialSpan: 9,
    specialText: 'done every 1st quarter of the year',
    q1t: '166', q1a: '166', q1p: '100%',
    major_final_output: 'Occupancy',
    performance_indicator: 'Renew',
    annual_target: '166',
    year: 2025,
  },
  {
    id: 'opif_a_03',
    section: 'A',
    col3: 'Optimal Revenue',
    col4: 'Occupancy',
    col5: 'No. of Lease Contract released',
    col6: 'New',
    col7: '10',
    actual: '5',
    semi: '3',
    q1t: '3', q1a: '3', q1p: '100%',
    q2t: '2', q2a: '2', q2p: '100%',
    q3t: '3', q3a: '3', q3p: '100%',
    q4t: '2', q4a: '2', q4p: '100%',
    major_final_output: 'Occupancy',
    performance_indicator: 'New',
    annual_target: '10',
    year: 2025,
  },
  {
    id: 'opif_a_04',
    section: 'A',
    col3: 'Optimal Revenue',
    col4: 'Occupancy',
    col5: 'No. of Lease Contract released',
    col6: 'Renew',
    col7: '166',
    actual: '166',
    semi: '166',
    specialSpan: 9,
    specialText: 'done every 1st quarter of the year',
    q1t: '166', q1a: '166', q1p: '100%',
    major_final_output: 'Occupancy',
    performance_indicator: 'Renew',
    annual_target: '166',
    year: 2025,
  },
  {
    id: 'opif_a_05',
    section: 'A',
    col3: 'Market Operation',
    col4: 'Stall Monitoring & Inspection',
    col5: 'No. of stalls inspected & monitored',
    col6: '243',
    col7: '243',
    actual: '243',
    semi: '243',
    q1t: '243', q1a: '243', q1p: '100%',
    q2t: '243', q2a: '246', q2p: '101%',
    q3t: '243', q3a: '245', q3p: '101%',
    q4t: '243', q4a: '', q4p: '',
    major_final_output: 'Stall Monitoring & Inspection',
    performance_indicator: '243',
    annual_target: '243',
    year: 2025,
  },
  {
    id: 'opif_a_06',
    section: 'A',
    col3: 'Market Operation',
    col4: 'Open Space Monitoring',
    col5: 'No. of transient vendors facilitated/monitored in Barangays (Poblacion, Malandag & Banate)',
    col6: '162',
    col7: '162',
    actual: '162',
    semi: '191',
    q1t: '162', q1a: '191', q1p: '118%',
    q2t: '162', q2a: '193', q2p: '119%',
    q3t: '162', q3a: '196', q3p: '121%',
    q4t: '162', q4a: '', q4p: '',
    major_final_output: 'Open Space Monitoring',
    performance_indicator: '162',
    annual_target: '162',
    year: 2025,
  },
  {
    id: 'opif_a_07',
    section: 'A',
    col3: 'Sanitary, Orderly & Safety',
    col4: 'Zoning:',
    col5: 'Administration of proper market stalls sectioning',
    col6: 'No. of market stalls properly administered as to its section',
    col7: '243',
    actual: '243',
    semi: '243',
    q1t: '243', q1a: '243', q1p: '100%',
    q2t: '243', q2a: '246', q2p: '101%',
    q3t: '243', q3a: '245', q3p: '101%',
    q4t: '', q4a: '', q4p: '',
    major_final_output: 'Zoning:',
    performance_indicator: 'No. of market stalls properly administered as to its section',
    annual_target: '243',
    year: 2025,
  },
  {
    id: 'opif_a_08',
    section: 'A',
    col3: 'Sanitary, Orderly & Safety',
    col4: 'Facility:',
    col5: 'Supervision and maintenance of cleanliness & proper sanitation of public market stalls and its premises',
    col6: 'No. of stalls supervised & maintained as to its premise cleanliness & proper sanitation',
    col7: '243',
    actual: '243',
    semi: '243',
    q1t: '243', q1a: '243', q1p: '100%',
    q2t: '243', q2a: '246', q2p: '101%',
    q3t: '243', q3a: '245', q3p: '101%',
    q4t: '', q4a: '', q4p: '',
    major_final_output: 'Facility:',
    performance_indicator: 'No. of stalls supervised & maintained as to its premise cleanliness & proper sanitation',
    annual_target: '243',
    year: 2025,
  },
  {
    id: 'opif_a_09',
    section: 'A',
    col3: 'Sanitary, Orderly & Safety',
    col4: 'Security:',
    col5: 'Conduct monitoring & supervision of peace and security in the public market premises',
    col6: 'No. of untoward incidence/cases in the public market premises',
    col7: '0',
    actual: '0',
    semi: '0',
    q1t: '0', q1a: '0', q1p: '100%',
    q2t: '0', q2a: '0', q2p: '100%',
    q3t: '0', q3a: '0', q3p: '100%',
    q4t: '0', q4a: '0', q4p: '100%',
    major_final_output: 'Security:',
    performance_indicator: 'No. of untoward incidence/cases in the public market premises',
    annual_target: '0',
    year: 2025,
  },
  {
    id: 'opif_a_10',
    section: 'A',
    col3: 'Regulatory Functions',
    col4: 'Statistical Data:',
    col5: 'Prepare statistical data on prevailing prices of goods in the public market',
    col6: 'No. of statistical data on prevailing prices of goods in the public market prepared once a week',
    col7: '52',
    actual: '26',
    semi: '13',
    q1t: '13', q1a: '13', q1p: '100%',
    q2t: '13', q2a: '14', q2p: '108%',
    q3t: '13', q3a: '13', q3p: '100%',
    q4t: '13', q4a: '14', q4p: '108%',
    major_final_output: 'Statistical Data:',
    performance_indicator: 'No. of statistical data on prevailing prices of goods in the public market prepared once a week',
    annual_target: '52',
    year: 2025,
  },
  {
    id: 'opif_a_11',
    section: 'A',
    col3: 'Regulatory Functions',
    col4: 'Stall Rental:',
    col5: 'Monitoring of stall rental payment',
    col6: 'No. of stall rental payment monitored',
    col7: '243',
    actual: '243',
    semi: '243',
    q1t: '243', q1a: '243', q1p: '100%',
    q2t: '243', q2a: '246', q2p: '101%',
    q3t: '243', q3a: '245', q3p: '101%',
    q4t: '', q4a: '', q4p: '',
    major_final_output: 'Stall Rental:',
    performance_indicator: 'No. of stall rental payment monitored',
    annual_target: '243',
    year: 2025,
  },

  // SECTION B: SLAUGHTER HOUSE MANAGEMENT (4 rows)
  {
    id: 'opif_b_01',
    section: 'B',
    col3: 'Regulatory Functions',
    col4: 'Meat Monitoring & Inspection',
    col5: 'Conduct of ante mortem and evisceration inspection',
    col6: 'No. of slaughtered animals conducted with ante mortem and evisceration inspection',
    col7: '913',
    actual: '457',
    semi: '228',
    q1t: '648', q1a: '', q1p: '284%',
    q2t: '229', q2a: '671', q2p: '293%',
    q3t: '228', q3a: '256', q3p: '112%',
    q4t: '229', q4a: '392', q4p: '171%',
    major_final_output: 'Meat Monitoring & Inspection',
    performance_indicator: 'No. of slaughtered animals conducted with ante mortem and evisceration inspection',
    annual_target: '913',
    year: 2025,
  },
  {
    id: 'opif_b_02',
    section: 'B',
    col3: 'Regulatory Functions',
    col4: 'Meat Monitoring & Inspection',
    col5: 'Issuance of Meat Inspection Certificate',
    col6: 'No. of Meat Inspection Certificate issued',
    col7: '913',
    actual: '457',
    semi: '228',
    q1t: '648', q1a: '', q1p: '284%',
    q2t: '229', q2a: '671', q2p: '293%',
    q3t: '228', q3a: '256', q3p: '112%',
    q4t: '229', q4a: '392', q4p: '171%',
    major_final_output: 'Meat Monitoring & Inspection',
    performance_indicator: 'No. of Meat Inspection Certificate issued',
    annual_target: '913',
    year: 2025,
  },
  {
    id: 'opif_b_03',
    section: 'B',
    col3: 'Regulatory Functions',
    col4: 'Meat Monitoring & Inspection',
    col5: 'Conduct of Meetings, Seminars to meat vendors & butchers',
    col6: 'No. of Meetings, Seminars to meat vendors & butchers conducted',
    col7: '4',
    actual: '2',
    semi: '1',
    q1t: '1', q1a: '', q1p: '100%',
    q2t: '1', q2a: '2', q2p: '200%',
    q3t: '1', q3a: '1', q3p: '100%',
    q4t: '1', q4a: '2', q4p: '200%',
    major_final_output: 'Meat Monitoring & Inspection',
    performance_indicator: 'No. of Meetings, Seminars to meat vendors & butchers conducted',
    annual_target: '4',
    year: 2025,
  },
  {
    id: 'opif_b_04',
    section: 'B',
    col3: 'Sanitation & Maintenance',
    col4: 'Sanitation & Maintenance',
    col5: 'Monitoring & inspection of proper hygiene for butchers, slaughter house premises including scalding area',
    col6: 'No. of days inspection and monitoring of proper hygiene for butchers, slaughter house premises including scalding area done',
    col7: '363',
    actual: '182',
    semi: '90',
    q1t: '91', q1a: '', q1p: '101%',
    q2t: '90', q2a: '91', q2p: '101%',
    q3t: '91', q3a: '92', q3p: '101%',
    q4t: '90', q4a: '92', q4p: '102%',
    major_final_output: 'Sanitation & Maintenance',
    performance_indicator: 'No. of days inspection and monitoring of proper hygiene for butchers, slaughter house premises including scalding area done',
    annual_target: '363',
    year: 2025,
  },

  // SECTION C: CEMETERY MANAGEMENT (2 rows)
  {
    id: 'opif_c_01',
    section: 'C',
    col3: 'Land Utilization',
    col4: 'Occupancy',
    col5: 'No. of graveyards facilitated/Allocated for occupancy based on the existing Plan of the Cemetery',
    col6: '',
    col7: '40',
    actual: '20',
    semi: '10',
    q1t: '15', q1a: '', q1p: '150%',
    q2t: '10', q2a: '20', q2p: '200%',
    q3t: '10', q3a: '18', q3p: '180%',
    q4t: '10', q4a: '19', q4p: '190%',
    major_final_output: 'Occupancy',
    performance_indicator: 'No. of graveyards facilitated/Allocated for occupancy based on the existing Plan of the Cemetery',
    annual_target: '40',
    year: 2025,
  },
  {
    id: 'opif_c_02',
    section: 'C',
    col3: 'Land Utilization',
    col4: 'Maintenance of 3.6 has. of land area',
    col5: '100% of 3.6 has. of land area for cemetery were maintained at least once a every quarter',
    col6: '',
    col7: '3.6',
    actual: '3.6',
    semi: '3.6',
    q1t: '3.6', q1a: '', q1p: '100%',
    q2t: '3.6', q2a: '3.6', q2p: '100%',
    q3t: '3.6', q3a: '3.6', q3p: '100%',
    q4t: '3.6', q4a: '3.6', q4p: '100%',
    major_final_output: 'Maintenance of 3.6 has. of land area',
    performance_indicator: '100% of 3.6 has. of land area for cemetery were maintained at least once a every quarter',
    annual_target: '3.6',
    year: 2025,
  },

  // SECTION D: TRANSPORT TERMINAL MANAGEMENT (4 rows)
  {
    id: 'opif_d_01',
    section: 'D',
    col3: 'Terminal Operation',
    col4: 'Public Terminal Monitoring & Inspection',
    col5: 'No. of Public Terminal Monitored & Inspected 3X a week',
    col6: '',
    col7: '4',
    actual: '4',
    semi: '4',
    q1t: '4', q1a: '', q1p: '100%',
    q2t: '4', q2a: '4', q2p: '100%',
    q3t: '4', q3a: '4', q3p: '100%',
    q4t: '4', q4a: '4', q4p: '100%',
    major_final_output: 'Public Terminal Monitoring & Inspection',
    performance_indicator: 'No. of Public Terminal Monitored & Inspected 3X a week',
    annual_target: '4',
    year: 2025,
  },
  {
    id: 'opif_d_02',
    section: 'D',
    col3: 'Terminal Operation',
    col4: 'Transport Organizations monitoring & assistance',
    col5: 'No. of Transport Organizations monitored & assisted as to compliance with the REEC quarterly',
    col6: '',
    col7: '15',
    actual: '15',
    semi: '15',
    q1t: '18', q1a: '', q1p: '120%',
    q2t: '15', q2a: '18', q2p: '120%',
    q3t: '15', q3a: '18', q3p: '120%',
    q4t: '15', q4a: '18', q4p: '120%',
    major_final_output: 'Transport Organizations monitoring & assistance',
    performance_indicator: 'No. of Transport Organizations monitored & assisted as to compliance with the REEC quarterly',
    annual_target: '15',
    year: 2025,
  },
  {
    id: 'opif_d_03',
    section: 'D',
    col3: 'Regulatory Functions',
    col4: 'Monitoring of Parking Fees',
    col5: 'No. of vehicles monitored as to parking fee payment',
    col6: '',
    col7: '4,642',
    actual: '4,642',
    semi: '4,642',
    q1t: '7,643', q1a: '', q1p: '165%',
    q2t: '4,642', q2a: '7,650', q2p: '165%',
    q3t: '4,642', q3a: '7,435', q3p: '160%',
    q4t: '4,642', q4a: '7,555', q4p: '163%',
    major_final_output: 'Monitoring of Parking Fees',
    performance_indicator: 'No. of vehicles monitored as to parking fee payment',
    annual_target: '4,642',
    year: 2025,
  },
  {
    id: 'opif_d_04',
    section: 'D',
    col3: 'Regulatory Functions',
    col4: 'Information, Education Campaign',
    col5: 'No. of Meetings & Posting of IEC Materials conducted quarterly',
    col6: '',
    col7: '6',
    actual: '3',
    semi: '2',
    q1t: '4', q1a: '', q1p: '200%',
    q2t: '1', q2a: '3', q2p: '300%',
    q3t: '2', q3a: '3', q3p: '150%',
    q4t: '1', q4a: '2', q4p: '200%',
    major_final_output: 'Information, Education Campaign',
    performance_indicator: 'No. of Meetings & Posting of IEC Materials conducted quarterly',
    annual_target: '6',
    year: 2025,
  },

  // SECTION E: ADMINISTRATIVE SERVICES (6 rows)
  {
    id: 'opif_e_01',
    section: 'E',
    col3: '',
    col4: 'Communications, Memos & Activity Designs',
    col5: 'Prepare Communications, Memos, Activity Designs & Project Proposals',
    col6: 'No. of Communications, Memos, Activity Designs & Project Proposals prepared and submitted to proper agencies w/n the time frame',
    col7: '20',
    actual: '10',
    semi: '5',
    q1t: '11', q1a: '', q1p: '220%',
    q2t: '5', q2a: '7', q2p: '140%',
    q3t: '5', q3a: '5', q3p: '100%',
    q4t: '5', q4a: '6', q4p: '120%',
    major_final_output: 'Communications, Memos & Activity Designs',
    performance_indicator: 'No. of Communications, Memos, Activity Designs & Project Proposals prepared and submitted to proper agencies w/n the time frame',
    annual_target: '20',
    year: 2025,
  },
  {
    id: 'opif_e_02',
    section: 'E',
    col3: '',
    col4: 'Annual Procurement Plan (APP)',
    col5: 'Prepare & recommends for approval of APP',
    col6: 'Prepared and recommended for approval of 1 APP within time frame',
    col7: '1',
    actual: '1',
    semi: '1',
    specialSpan: 9,
    specialText: 'done every 1st quarter of the year',
    q1t: '1', q1a: '', q1p: '100%',
    major_final_output: 'Annual Procurement Plan (APP)',
    performance_indicator: 'Prepared and recommended for approval of 1 APP within time frame',
    annual_target: '1',
    year: 2025,
  },
  {
    id: 'opif_e_03',
    section: 'E',
    col3: '',
    col4: 'Purchase Request, Vouchers',
    col5: 'Prepare, facilitate and submit Purchase Request and Vouchers',
    col6: 'Purchase Request (PR) and Vouchers prepared, facilitated and submitted w/n the time frame',
    col7: '12',
    actual: '6',
    semi: '3',
    q1t: '6', q1a: '', q1p: '200%',
    q2t: '4', q2a: '9', q2p: '225%',
    q3t: '3', q3a: '3', q3p: '100%',
    q4t: '2', q4a: '3', q4p: '150%',
    major_final_output: 'Purchase Request, Vouchers',
    performance_indicator: 'Purchase Request (PR) and Vouchers prepared, facilitated and submitted w/n the time frame',
    annual_target: '12',
    year: 2025,
  },
  {
    id: 'opif_e_04',
    section: 'E',
    col3: '',
    col4: 'Itinerary of Travels and liquidation Reports',
    col5: 'Prepare itinerary of travels and liquidation reports',
    col6: 'Prepared 4 itinerary of travels and liquidation reports within time frame',
    col7: '4',
    actual: '2',
    semi: '1',
    q1t: '3', q1a: '', q1p: '300%',
    q2t: '1', q2a: '4', q2p: '400%',
    q3t: '1', q3a: '2', q3p: '200%',
    q4t: '1', q4a: '2', q4p: '200%',
    major_final_output: 'Itinerary of Travels and liquidation Reports',
    performance_indicator: 'Prepared 4 itinerary of travels and liquidation reports within time frame',
    annual_target: '4',
    year: 2025,
  },
  {
    id: 'opif_e_05',
    section: 'E',
    col3: '',
    col4: 'Archiving/Filing',
    col5: 'Archiving/filing of office documents',
    col6: '80 orders, issuances, incoming & out going communications, resolutions and other pertinent documents archived/filed within time frame',
    col7: '140',
    actual: '70',
    semi: '35',
    q1t: '64', q1a: '', q1p: '183%',
    q2t: '35', q2a: '42', q2p: '120%',
    q3t: '35', q3a: '56', q3p: '160%',
    q4t: '35', q4a: '48', q4p: '137%',
    major_final_output: 'Archiving/Filing',
    performance_indicator: '80 orders, issuances, incoming & out going communications, resolutions and other pertinent documents archived/filed within time frame',
    annual_target: '140',
    year: 2025,
  },
  {
    id: 'opif_e_06',
    section: 'E',
    col3: '',
    col4: 'Workplace Management',
    col5: '5 S Compliant',
    col6: '5 S Compliant',
    col7: '1',
    actual: '1',
    semi: '1',
    q1t: '1', q1a: '', q1p: '100%',
    q2t: '1', q2a: '1', q2p: '100%',
    q3t: '1', q3a: '1', q3p: '100%',
    q4t: '1', q4a: '1', q4p: '100%',
    major_final_output: 'Workplace Management',
    performance_indicator: '5 S Compliant',
    annual_target: '1',
    year: 2025,
  },
];

export const initialMarketGuards: MarketGuard[] = [
  {
    guard_id: 'G-101',
    guard_name: 'Roberto Alcantara',
    rank_title: 'SO2',
    default_area: 'Gate 1 & Main Entrance',
    contact_no: '0917-555-0101',
    status: 'Active',
  },
  {
    guard_id: 'G-102',
    guard_name: 'Maria Santos',
    rank_title: 'SO1',
    default_area: 'Food Terminal & Dry Goods',
    contact_no: '0917-555-0102',
    status: 'Active',
  },
  {
    guard_id: 'G-103',
    guard_name: 'Danilo Cruz',
    rank_title: 'SO1',
    default_area: 'Public Market Parking Area',
    contact_no: '0917-555-0103',
    status: 'Active',
  },
  {
    guard_id: 'G-104',
    guard_name: 'Carlito Ramos',
    rank_title: 'SO1',
    default_area: 'Meat & Wet Section Alley',
    contact_no: '0917-555-0104',
    status: 'Active',
  },
  {
    guard_id: 'G-105',
    guard_name: 'Marcos Dalisay',
    rank_title: 'Team Leader',
    default_area: 'Market Security Guardhouse',
    contact_no: '0917-555-0105',
    status: 'Active',
  },
  {
    guard_id: 'G-106',
    guard_name: 'Antonio Reyes',
    rank_title: 'SO1',
    default_area: 'Perimeter Night Patrol',
    contact_no: '0917-555-0106',
    status: 'Active',
  },
];

export const initialCsuReports: CsuDailyReport[] = [
  {
    id: 'csu_rep_01',
    report_date: '2024-09-08',
    day_of_week: 'Sunday',
    shift: '1st Shift (0600H - 1400H)',
    area_covered: 'Public Market Main Building & Wet Section Perimeter',
    summary_activities: 'Conducted regular security foot patrols, assisted elderly market-goers, monitored vendor unloading operations, and verified orderly tricycle queues at the entrance.',
    turnover_notes: 'Remind 2nd shift to monitor wet section drainage gates and ensure perimeter lights are activated by 1730H.',
    prep_name: 'SO2 Roberto Alcantara',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Gate 1 & Parking',
        time_in: '05:45',
        time_out: '14:00',
        remarks: 'On duty on time',
      },
      {
        guard_id: 'G-104',
        guard_name: 'Carlito Ramos',
        assigned_area: 'Wet Section Alley',
        time_in: '05:50',
        time_out: '14:00',
        remarks: 'Assisted market sanitation crew',
      },
    ],
    incident_data: [],
    violations_data: [
      {
        identifier: 'Transient Vendor #14',
        violation: 'Blocking pedestrian lane with produce crates',
        action_taken: 'Verbally reprimanded; vendor voluntarily cleared walkway',
        remarks: 'First offense',
      },
    ],
    lost_found_data: [
      {
        description: 'Black leather wallet with PhilHealth ID',
        found_by: 'Guard Alcantara (near Stall G-02-A)',
        claimed_by: 'Juanita Dela Cruz',
        status: 'Claimed',
      },
    ],
    created_at: '2024-09-08T14:10:00Z',
  },
  {
    id: 'csu_rep_02',
    report_date: '2024-09-07',
    day_of_week: 'Saturday',
    shift: '1st Shift (0600H - 1400H)',
    area_covered: 'Public Market Main Building, Food Terminal & Parking Area',
    summary_activities: 'Supervised Saturday market day foot traffic, maintained orderly vehicular flow at the Land Bank perimeter, assisted senior citizens.',
    turnover_notes: 'All terminal gates secured; night lights operational.',
    prep_name: 'SO2 Roberto Alcantara',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Gate 1 & Main Entrance',
        time_in: '05:50',
        time_out: '14:00',
        remarks: 'Maintained gate queue',
      },
      {
        guard_id: 'G-102',
        guard_name: 'Maria Santos',
        assigned_area: 'Food Terminal & Dry Goods',
        time_in: '06:00',
        time_out: '14:00',
        remarks: 'Foot patrol on 2nd floor',
      },
    ],
    incident_data: [
      {
        time: '09:30',
        location: 'Gate 1 Tricycle Bay',
        type: 'Minor Traffic Jam',
        description: 'Tricycle parked across unloading area. Driver directed to designated TODA holding line.',
        status: 'Resolved',
      },
    ],
    violations_data: [],
    lost_found_data: [],
    created_at: '2024-09-07T14:05:00Z',
  },
  {
    id: 'csu_rep_03',
    report_date: '2024-09-06',
    day_of_week: 'Friday',
    shift: '2nd Shift (1400H - 2200H)',
    area_covered: 'Public Market Perimeter & Meat Section',
    summary_activities: 'Conducted night lock-up inspection of all meat stalls and Section G stalls. Verified electrical breakers.',
    turnover_notes: 'All main gates padlocked at 2130H. Roving guard stationed at triangular post.',
    prep_name: 'SO1 Carlito Ramos',
    prep_title: 'Duty Guard / Prepared By',
    ver_name: 'TL Marcos Dalisay',
    ver_title: 'Team Leader on Duty',
    app_name: 'Hon. Market Administrator',
    app_title: 'Market Administrator',
    personnel_data: [
      {
        guard_id: 'G-104',
        guard_name: 'Carlito Ramos',
        assigned_area: 'Meat & Wet Section Lockup',
        time_in: '13:55',
        time_out: '22:00',
        remarks: 'Completed closing inspection',
      },
      {
        guard_id: 'G-101',
        guard_name: 'Roberto Alcantara',
        assigned_area: 'Perimeter Roving',
        time_in: '14:00',
        time_out: '22:00',
        remarks: 'Assisted night lockup',
      },
    ],
    incident_data: [],
    violations_data: [],
    lost_found_data: [],
    created_at: '2024-09-06T22:15:00Z',
  },
];

// -----------------------------------------------------------------------------
// INVENTORY MANAGEMENT INITIAL DATA
// -----------------------------------------------------------------------------
export const initialInventoryItems: InventoryItem[] = [];

export const initialInventoryTransactions: InventoryTransaction[] = [];


